language: node_js
branches:
  only:
    - master
cache:
  directories:
    - "$HOME/.npm"
node_js:
  - "10"
script:
  - npm install --global codecov
  - npm test
  - npm run lint
  - npm audit
after_success:
  - codecov
